[colors.bright]
black = "#a0a1a1"
blue = "#7d9db4"
cyan = "#d4cbc0"
green = "#a4b23a"
magenta = "#b8ada1"
red = "#72a15c"
white = "#f2f3f3"
yellow = "#a09f7c"

[colors.normal]
black = "#151312"
blue = "#6D91AB"
cyan = "#CABEB1"
green = "#939F34"
magenta = "#ADA193"
red = "#679153"
white = "#e5e6e7"
yellow = "#95946D"

[colors.primary]
background = "#151312"
foreground = "#e5e6e7"
